import { TreeInfo } from "./treeData";
import neemImg from "@/assets/trees/neem.jpg";
import banyanImg from "@/assets/trees/banyan.jpg";
import mangoImg from "@/assets/trees/mango.jpg";
import coconutImg from "@/assets/trees/coconut.jpg";
import peepalImg from "@/assets/trees/peepal.jpg";
import tulsiImg from "@/assets/trees/tulsi.jpg";
import oakImg from "@/assets/trees/oak.jpg";
import pineImg from "@/assets/trees/pine.jpg";
import mahoganyImg from "@/assets/trees/mahogany.jpg";
import teakImg from "@/assets/trees/teak.jpg";
import bambooImg from "@/assets/trees/bamboo.jpg";
import cedarImg from "@/assets/trees/cedar.jpg";
import eucalyptusImg from "@/assets/trees/eucalyptus.jpg";
import jackfruitImg from "@/assets/trees/jackfruit.jpg";
import guavaImg from "@/assets/trees/guava.jpg";
import papayaImg from "@/assets/trees/papaya.jpg";
import lemonImg from "@/assets/trees/lemon.jpg";
import orangeImg from "@/assets/trees/orange.jpg";
import pomegranateImg from "@/assets/trees/pomegranate.jpg";
import figImg from "@/assets/trees/fig.jpg";
import tamarindImg from "@/assets/trees/tamarind.jpg";
import jamunImg from "@/assets/trees/jamun.jpg";
import amlaImg from "@/assets/trees/amla.jpg";
import curryLeafImg from "@/assets/trees/curry-leaf.jpg";
import drumstickImg from "@/assets/trees/drumstick.jpg";
import arecaImg from "@/assets/trees/areca.jpg";
import betelNutImg from "@/assets/trees/betel-nut.jpg";
import palmImg from "@/assets/trees/palm.jpg";
import sandalwoodImg from "@/assets/trees/sandalwood.jpg";
import deodarImg from "@/assets/trees/deodar.jpg";
import chirImg from "@/assets/trees/chir.jpg";
import firImg from "@/assets/trees/fir.jpg";
import spruceImg from "@/assets/trees/spruce.jpg";
import mapleImg from "@/assets/trees/maple.jpg";
import birchImg from "@/assets/trees/birch.jpg";
import willowImg from "@/assets/trees/willow.jpg";
import poplarImg from "@/assets/trees/poplar.jpg";
import elmImg from "@/assets/trees/elm.jpg";
import ashImg from "@/assets/trees/ash.jpg";
import walnutImg from "@/assets/trees/walnut.jpg";
import chestnutImg from "@/assets/trees/chestnut.jpg";
import cherryImg from "@/assets/trees/cherry.jpg";
import plumImg from "@/assets/trees/plum.jpg";
import peachImg from "@/assets/trees/peach.jpg";
import apricotImg from "@/assets/trees/apricot.jpg";
import almondImg from "@/assets/trees/almond.jpg";
import cashewImg from "@/assets/trees/cashew.jpg";
import pistachioImg from "@/assets/trees/pistachio.jpg";
import oliveImg from "@/assets/trees/olive.jpg";
import dateImg from "@/assets/trees/date.jpg";
import avocadoImg from "@/assets/trees/avocado.jpg";
import custardAppleImg from "@/assets/trees/custard-apple.jpg";
import sapotaImg from "@/assets/trees/sapota.jpg";
import litchiImg from "@/assets/trees/litchi.jpg";
import longanImg from "@/assets/trees/longan.jpg";
import rambutanImg from "@/assets/trees/rambutan.jpg";
// New unique tree images
import durianImg from "@/assets/trees/durian.jpg";
import mangosteenImg from "@/assets/trees/mangosteen.jpg";
import starFruitImg from "@/assets/trees/star-fruit.jpg";
import dragonFruitImg from "@/assets/trees/dragon-fruit.jpg";
import passionFruitImg from "@/assets/trees/passion-fruit.jpg";
import kiwiImg from "@/assets/trees/kiwi.jpg";
import persimmonImg from "@/assets/trees/persimmon.jpg";
import mulberryImg from "@/assets/trees/mulberry.jpg";
import blackberryImg from "@/assets/trees/blackberry.jpg";
import raspberryImg from "@/assets/trees/raspberry.jpg";
import gooseberryImg from "@/assets/trees/gooseberry.jpg";
import blueberryImg from "@/assets/trees/blueberry.jpg";
import cranberryImg from "@/assets/trees/cranberry.jpg";
import elderberryImg from "@/assets/trees/elderberry.jpg";
import hawthornImg from "@/assets/trees/hawthorn.jpg";
import juniperImg from "@/assets/trees/juniper.jpg";
import yewImg from "@/assets/trees/yew.jpg";
import sequoiaImg from "@/assets/trees/sequoia.jpg";
import redwoodImg from "@/assets/trees/redwood.jpg";
import cypressImg from "@/assets/trees/cypress.jpg";
import larchImg from "@/assets/trees/larch.jpg";
import hemlockImg from "@/assets/trees/hemlock.jpg";
import acaciaImg from "@/assets/trees/acacia.jpg";
import mimosaImg from "@/assets/trees/mimosa.jpg";
import wattleImg from "@/assets/trees/wattle.jpg";
import gumImg from "@/assets/trees/gum.jpg";
import bottlebrushImg from "@/assets/trees/bottlebrush.jpg";
import teaTreeImg from "@/assets/trees/tea-tree.jpg";
import manukaImg from "@/assets/trees/manuka.jpg";
import karriImg from "@/assets/trees/karri.jpg";
import jarrahImg from "@/assets/trees/jarrah.jpg";
import blackwoodImg from "@/assets/trees/blackwood.jpg";
import silverWattleImg from "@/assets/trees/silver-wattle.jpg";
import ironwoodImg from "@/assets/trees/ironwood.jpg";
import ebonyImg from "@/assets/trees/ebony.jpg";
import boxwoodImg from "@/assets/trees/boxwood.jpg";
import hollyImg from "@/assets/trees/holly.jpg";
import magnoliaImg from "@/assets/trees/magnolia.jpg";
import dogwoodImg from "@/assets/trees/dogwood.jpg";
import redbudImg from "@/assets/trees/redbud.jpg";
import smokeTreeImg from "@/assets/trees/smoke-tree.jpg";
import rosewoodImg from "@/assets/trees/rosewood.jpg";
import sycamoreImg from "@/assets/trees/sycamore.jpg";
import hickoryImg from "@/assets/trees/hickory.jpg";

// Extended tree library with 100 trees - all with unique images
export const expandedTreeData: TreeInfo[] = [
  // Original 6 trees
  { id: "neem", nameEn: "Neem Tree", nameTe: "వేప చెట్టు", nameHi: "नीम का पेड़", benefits: ["Air purification", "Medicinal properties", "Natural pesticide", "Shade provider"], benefitsTe: ["గాలి శుద్ధి", "ఔషధ గుణాలు", "సహజ పురుగుమందు", "నీడ అందించడం"], benefitsHi: ["वायु शुद्धिकरण", "औषधीय गुण", "प्राकृतिक कीटनाशक", "छाया प्रदाता"], growthTime: "3-5 years", soilType: "Dry soil", maintenance: "Low water", co2Absorption: 25, oxygenProduction: 260, image: neemImg },
  { id: "banyan", nameEn: "Banyan Tree", nameTe: "మర్రి చెట్టు", nameHi: "बरगद का पेड़", benefits: ["Large canopy", "Oxygen production", "Wildlife habitat", "Cultural significance"], benefitsTe: ["పెద్ద చాప", "ఆక్సిజన్ ఉత్పత్తి", "వన్యజీవుల ఆవాసం", "సాంస్కృతిక ప్రాముఖ్యత"], benefitsHi: ["बड़ी छतरी", "ऑक्सीजन उत्पादन", "वन्यजीव आवास", "सांस्कृतिक महत्व"], growthTime: "5-10 years", soilType: "Rich soil", maintenance: "Regular water", co2Absorption: 50, oxygenProduction: 500, image: banyanImg },
  { id: "mango", nameEn: "Mango Tree", nameTe: "మామిడి చెట్టు", nameHi: "आम का पेड़", benefits: ["Delicious fruits", "Dense foliage", "Shade", "Economic value"], benefitsTe: ["రుచికరమైన పండ్లు", "దట్టమైన ఆకులు", "నీడ", "ఆర్థిక విలువ"], benefitsHi: ["स्वादिष्ट फल", "घना पत्ते", "छाया", "आर्थिक मूल्य"], growthTime: "4-6 years", soilType: "Sandy loam", maintenance: "Moderate water", co2Absorption: 28, oxygenProduction: 300, image: mangoImg },
  { id: "coconut", nameEn: "Coconut Tree", nameTe: "కొబ్బరి చెట్టు", nameHi: "नारियल का पेड़", benefits: ["Coconut production", "Versatile uses", "Coastal protection", "Income source"], benefitsTe: ["కొబ్బరి ఉత్పత్తి", "బహుముఖ వినియోగాలు", "తీర రక్షణ", "ఆదాయ వనరు"], benefitsHi: ["नारियल उत्पादन", "बहुमुखी उपयोग", "तटीय सुरक्षा", "आय स्रोत"], growthTime: "5-7 years", soilType: "Sandy soil", maintenance: "Regular water", co2Absorption: 22, oxygenProduction: 250, image: coconutImg },
  { id: "peepal", nameEn: "Peepal Tree", nameTe: "రావి చెట్టు", nameHi: "पीपल का पेड़", benefits: ["24/7 oxygen", "Sacred tree", "Large shade", "Long lifespan"], benefitsTe: ["24/7 ఆక్సిజన్", "పవిత్ర చెట్టు", "పెద్ద నీడ", "దీర్ఘ జీవితకాలం"], benefitsHi: ["24/7 ऑक्सीजन", "पवित्र पेड़", "बड़ी छाया", "लंबा जीवनकाल"], growthTime: "4-6 years", soilType: "Various", maintenance: "Low", co2Absorption: 45, oxygenProduction: 450, image: peepalImg },
  { id: "tulsi", nameEn: "Tulsi", nameTe: "తులసి", nameHi: "तुलसी", benefits: ["Medicinal", "Air purification", "Aromatic", "Easy to grow"], benefitsTe: ["ఔషధ", "గాలి శుద్ధి", "సుగంధం", "సులభం"], benefitsHi: ["औषधीय", "वायु शुद्धिकरण", "सुगंधित", "आसान"], growthTime: "3-6 months", soilType: "Fertile soil", maintenance: "Regular water", co2Absorption: 2, oxygenProduction: 20, image: tulsiImg },
  // Trees 7-56 with unique images
  { id: "oak", nameEn: "Oak Tree", nameTe: "ఓక్ చెట్టు", nameHi: "ओक का पेड़", benefits: ["Strong wood", "Wildlife habitat", "Longevity", "Shade provider"], benefitsTe: ["బలమైన కలప", "వన్యజీవుల నివాసం", "దీర్ఘాయువు", "నీడ"], benefitsHi: ["मजबूत लकड़ी", "वन्यजीव आवास", "दीर्घायु", "छाया"], growthTime: "5-8 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 30, oxygenProduction: 320, image: oakImg },
  { id: "pine", nameEn: "Pine Tree", nameTe: "పైన్ చెట్టు", nameHi: "पाइन का पेड़", benefits: ["Evergreen", "Timber production", "Resin source", "Erosion control"], benefitsTe: ["శాశ్వత ఆకులు", "కలప ఉత్పత్తి", "రాళ్ళ మూలం", "కోత నియంత్రణ"], benefitsHi: ["सदाबहार", "लकड़ी उत्पादन", "रेजिन स्रोत", "कटाव नियंत्रण"], growthTime: "4-6 years", soilType: "Sandy soil", maintenance: "Low", co2Absorption: 26, oxygenProduction: 280, image: pineImg },
  { id: "mahogany", nameEn: "Mahogany Tree", nameTe: "మహాగని చెట్టు", nameHi: "महोगनी का पेड़", benefits: ["Premium wood", "Fast growth", "High value", "Carbon sequestration"], benefitsTe: ["ప్రీమియం కలప", "వేగవంతమైన పెరుగుదల", "అధిక విలువ", "కార్బన్ నిల్వ"], benefitsHi: ["प्रीमियम लकड़ी", "तेज़ विकास", "उच्च मूल्य", "कार्बन संग्रहण"], growthTime: "6-8 years", soilType: "Loamy soil", maintenance: "Moderate", co2Absorption: 35, oxygenProduction: 370, image: mahoganyImg },
  { id: "teak", nameEn: "Teak Tree", nameTe: "టేకు చెట్టు", nameHi: "सागौन का पेड़", benefits: ["Durable wood", "Weather resistant", "High demand", "Long lifespan"], benefitsTe: ["మన్నికైన కలప", "వాతావరణ నిరోధకత", "అధిక డిమాండ్", "దీర్ఘ జీవితం"], benefitsHi: ["टिकाऊ लकड़ी", "मौसम प्रतिरोधी", "उच्च मांग", "लंबा जीवन"], growthTime: "7-10 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 40, oxygenProduction: 420, image: teakImg },
  { id: "bamboo", nameEn: "Bamboo", nameTe: "వెదురు", nameHi: "बांस", benefits: ["Fast growing", "Multiple uses", "Renewable resource", "Carbon absorption"], benefitsTe: ["వేగంగా పెరుగుతుంది", "అనేక ఉపయోగాలు", "పునరుత్పాదక వనరు", "కార్బన్ శోషణ"], benefitsHi: ["तेजी से बढ़ता", "कई उपयोग", "नवीकरणीय संसाधन", "कार्बन अवशोषण"], growthTime: "3-5 years", soilType: "Fertile soil", maintenance: "Regular water", co2Absorption: 35, oxygenProduction: 360, image: bambooImg },
  { id: "cedar", nameEn: "Cedar Tree", nameTe: "సీడార్ చెట్టు", nameHi: "देवदार का पेड़", benefits: ["Aromatic wood", "Insect repellent", "Beautiful foliage", "Long-lasting"], benefitsTe: ["సుగంధ కలప", "కీటక నివారణ", "అందమైన ఆకులు", "దీర్ఘకాలం"], benefitsHi: ["सुगंधित लकड़ी", "कीट प्रतिरोधी", "सुंदर पत्ते", "लंबे समय तक"], growthTime: "5-7 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 32, oxygenProduction: 340, image: cedarImg },
  { id: "eucalyptus", nameEn: "Eucalyptus Tree", nameTe: "యూకలిప్టస్ చెట్టు", nameHi: "नीलगिरी का पेड़", benefits: ["Fast growth", "Medicinal oil", "Pulp production", "Windbreak"], benefitsTe: ["వేగవంతమైన పెరుగుదల", "ఔషధ నూనె", "గుజ్జు ఉత్పత్తి", "గాలి అవరోధం"], benefitsHi: ["तेज़ विकास", "औषधीय तेल", "लुगदी उत्पादन", "हवा अवरोध"], growthTime: "3-5 years", soilType: "Various", maintenance: "Low", co2Absorption: 28, oxygenProduction: 290, image: eucalyptusImg },
  { id: "jackfruit", nameEn: "Jackfruit Tree", nameTe: "పనస చెట్టు", nameHi: "कटहल का पेड़", benefits: ["Large fruits", "Nutritious", "Timber wood", "Shade"], benefitsTe: ["పెద్ద పండ్లు", "పోషకమైనది", "కలప కలప", "నీడ"], benefitsHi: ["बड़े फल", "पौष्टिक", "इमारती लकड़ी", "छाया"], growthTime: "5-7 years", soilType: "Loamy soil", maintenance: "Moderate water", co2Absorption: 27, oxygenProduction: 285, image: jackfruitImg },
  { id: "guava", nameEn: "Guava Tree", nameTe: "జామ చెట్టు", nameHi: "अमरूद का पेड़", benefits: ["Vitamin C rich", "Easy to grow", "Multiple harvests", "Medicinal leaves"], benefitsTe: ["విటమిన్ సి సమృద్ధి", "పెంచడం సులభం", "అనేక పంటలు", "ఔషధ ఆకులు"], benefitsHi: ["विटामिन सी युक्त", "उगाना आसान", "कई फसलें", "औषधीय पत्तियां"], growthTime: "3-4 years", soilType: "Well-drained", maintenance: "Moderate water", co2Absorption: 20, oxygenProduction: 220, image: guavaImg },
  { id: "papaya", nameEn: "Papaya Tree", nameTe: "బొప్పాయి చెట్టు", nameHi: "पपीता का पेड़", benefits: ["Fast fruiting", "Digestive enzyme", "Year-round production", "Space efficient"], benefitsTe: ["వేగంగా పండ్లు", "జీర్ణ ఎంజైం", "సంవత్సరం పొడవునా ఉత్పత్తి", "స్థల సామర్థ్యం"], benefitsHi: ["तेज़ फल", "पाचन एंजाइम", "साल भर उत्पादन", "स्थान कुशल"], growthTime: "1-2 years", soilType: "Fertile soil", maintenance: "Regular water", co2Absorption: 15, oxygenProduction: 180, image: papayaImg },
  { id: "lemon", nameEn: "Lemon Tree", nameTe: "నిమ్మ చెట్టు", nameHi: "नींबू का पेड़", benefits: ["Vitamin C", "Fresh fruit", "Aromatic", "Medicinal"], benefitsTe: ["విటమిన్ సి", "తాజా పండు", "సుగంధం", "ఔషధం"], benefitsHi: ["विटामिन सी", "ताजा फल", "सुगंधित", "औषधीय"], growthTime: "3-4 years", soilType: "Well-drained", maintenance: "Moderate water", co2Absorption: 18, oxygenProduction: 190, image: lemonImg },
  { id: "orange", nameEn: "Orange Tree", nameTe: "నారింజ చెట్టు", nameHi: "संतरा का पेड़", benefits: ["Vitamin C rich", "Sweet fruit", "Ornamental", "Fragrant blossoms"], benefitsTe: ["విటమిన్ సి సమృద్ధి", "తీయని పండు", "అలంకార", "సుగంధ పువ్వులు"], benefitsHi: ["विटामिन सी युक्त", "मीठा फल", "सजावटी", "सुगंधित फूल"], growthTime: "3-5 years", soilType: "Loamy soil", maintenance: "Regular water", co2Absorption: 19, oxygenProduction: 200, image: orangeImg },
  { id: "pomegranate", nameEn: "Pomegranate Tree", nameTe: "దానిమ్మ చెట్టు", nameHi: "अनार का पेड़", benefits: ["Antioxidants", "Healthy fruit", "Drought tolerant", "Beautiful flowers"], benefitsTe: ["యాంటీఆక్సిడెంట్లు", "ఆరోగ్యకర పండు", "కరువు సహనం", "అందమైన పువ్వులు"], benefitsHi: ["एंटीऑक्सीडेंट", "स्वस्थ फल", "सूखा सहिष्णु", "सुंदर फूल"], growthTime: "3-4 years", soilType: "Well-drained", maintenance: "Low water", co2Absorption: 17, oxygenProduction: 185, image: pomegranateImg },
  { id: "fig", nameEn: "Fig Tree", nameTe: "అంజూర చెట్టు", nameHi: "अंजीर का पेड़", benefits: ["Nutritious fruit", "Large leaves", "Shade provider", "Historical significance"], benefitsTe: ["పోషకమైన పండు", "పెద్ద ఆకులు", "నీడ అందించడం", "చారిత్రక ప్రాముఖ్యత"], benefitsHi: ["पौष्टिक फल", "बड़े पत्ते", "छाया प्रदाता", "ऐतिहासिक महत्व"], growthTime: "2-3 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 16, oxygenProduction: 180, image: figImg },
  { id: "tamarind", nameEn: "Tamarind Tree", nameTe: "చింత చెట్టు", nameHi: "इमली का पेड़", benefits: ["Tangy fruit", "Dense canopy", "Long-lived", "Culinary use"], benefitsTe: ["పులుపు పండు", "దట్టమైన శాఖలు", "దీర్ఘాయువు", "వంట వినియోగం"], benefitsHi: ["खट्टा फल", "घना छत्र", "दीर्घजीवी", "पाक उपयोग"], growthTime: "5-7 years", soilType: "Various", maintenance: "Low", co2Absorption: 30, oxygenProduction: 320, image: tamarindImg },
  { id: "jamun", nameEn: "Jamun Tree", nameTe: "నేరేడు చెట్టు", nameHi: "जामुन का पेड़", benefits: ["Diabetic friendly", "Antioxidants", "Cooling effect", "Wildlife food"], benefitsTe: ["మధుమేహ స్నేహపూర్వక", "యాంటీఆక్సిడెంట్లు", "చల్లని ప్రభావం", "వన్యజీవుల ఆహారం"], benefitsHi: ["मधुमेह के अनुकूल", "एंटीऑक्सीडेंट", "शीतलन प्रभाव", "वन्यजीव भोजन"], growthTime: "4-6 years", soilType: "Loamy soil", maintenance: "Moderate", co2Absorption: 24, oxygenProduction: 260, image: jamunImg },
  { id: "amla", nameEn: "Amla Tree", nameTe: "ఉసిరి చెట్టు", nameHi: "आंवला का पेड़", benefits: ["Super food", "Vitamin C boost", "Ayurvedic", "Hair care"], benefitsTe: ["సూపర్ ఫుడ్", "విటమిన్ సి బూస్ట్", "ఆయుర్వేద", "జుట్టు సంరక్షణ"], benefitsHi: ["सुपर फूड", "विटामिन सी बूस्ट", "आयुर्वेदिक", "बाल देखभाल"], growthTime: "3-5 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 21, oxygenProduction: 230, image: amlaImg },
  { id: "curry-leaf", nameEn: "Curry Leaf Tree", nameTe: "కరివేపాకు చెట్టు", nameHi: "करी पत्ता का पेड़", benefits: ["Culinary herb", "Aromatic", "Medicinal", "Easy to grow"], benefitsTe: ["వంట మూలిక", "సుగంధం", "ఔషధం", "పెంచడం సులభం"], benefitsHi: ["पाक जड़ी बूटी", "सुगंधित", "औषधीय", "उगाना आसान"], growthTime: "2-3 years", soilType: "Fertile soil", maintenance: "Regular water", co2Absorption: 12, oxygenProduction: 150, image: curryLeafImg },
  { id: "drumstick", nameEn: "Drumstick Tree", nameTe: "మునగ చెట్టు", nameHi: "सहजन का पेड़", benefits: ["Superfood", "Fast growing", "Nutrient rich", "Medicinal"], benefitsTe: ["సూపర్ఫుడ్", "వేగంగా పెరుగుతుంది", "పోషక సమృద్ధి", "ఔషధం"], benefitsHi: ["सुपरफूड", "तेजी से बढ़ता", "पोषक तत्व समृद्ध", "औषधीय"], growthTime: "1-2 years", soilType: "Sandy soil", maintenance: "Low", co2Absorption: 15, oxygenProduction: 170, image: drumstickImg },
  { id: "areca", nameEn: "Areca Palm", nameTe: "అరకు తాటి", nameHi: "सुपारी का पेड़", benefits: ["Betel nut production", "Ornamental", "Economic value", "Tropical beauty"], benefitsTe: ["వక్క ఉత్పత్తి", "అలంకార", "ఆర్థిక విలువ", "ఉష్ణమండల అందం"], benefitsHi: ["सुपारी उत्पादन", "सजावटी", "आर्थिक मूल्य", "उष्णकटिबंधीय सुंदरता"], growthTime: "4-6 years", soilType: "Rich soil", maintenance: "Regular water", co2Absorption: 20, oxygenProduction: 220, image: arecaImg },
  { id: "betel-nut", nameEn: "Betel Nut Tree", nameTe: "వక్క చెట్టు", nameHi: "सुपारी का पेड़", benefits: ["Nut production", "Tall palm", "Commercial crop", "Shade"], benefitsTe: ["గింజ ఉత్పత్తి", "ఎత్తైన తాటి", "వాణిజ్య పంట", "నీడ"], benefitsHi: ["अखरोट उत्पादन", "ऊंची ताड़", "व्यावसायिक फसल", "छाया"], growthTime: "5-7 years", soilType: "Loamy soil", maintenance: "Moderate", co2Absorption: 22, oxygenProduction: 240, image: betelNutImg },
  { id: "palm", nameEn: "Palm Tree", nameTe: "తాటి చెట్టు", nameHi: "ताड़ का पेड़", benefits: ["Tropical beauty", "Versatile uses", "Storm resistant", "Low maintenance"], benefitsTe: ["ఉష్ణమండల అందం", "బహుముఖ వినియోగాలు", "తుఫాను నిరోధకత", "తక్కువ నిర్వహణ"], benefitsHi: ["उष्णकटिबंधीय सुंदरता", "बहुमुखी उपयोग", "तूफान प्रतिरोधी", "कम रखरखाव"], growthTime: "4-6 years", soilType: "Sandy soil", maintenance: "Low", co2Absorption: 19, oxygenProduction: 210, image: palmImg },
  { id: "sandalwood", nameEn: "Sandalwood Tree", nameTe: "గంధం చెట్టు", nameHi: "चंदन का पेड़", benefits: ["Aromatic wood", "High value", "Perfume industry", "Sacred tree"], benefitsTe: ["సుగంధ కలప", "అధిక విలువ", "పరిమళ పరిశ్రమ", "పవిత్ర చెట్టు"], benefitsHi: ["सुगंधित लकड़ी", "उच्च मूल्य", "इत्र उद्योग", "पवित्र पेड़"], growthTime: "15-20 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 23, oxygenProduction: 250, image: sandalwoodImg },
  { id: "deodar", nameEn: "Deodar Cedar", nameTe: "దేవదారు", nameHi: "देवदार", benefits: ["Majestic tree", "Timber wood", "Himalayan native", "Ornamental"], benefitsTe: ["గంభీరమైన చెట్టు", "కలప కలప", "హిమాలయ మూలికం", "అలంకార"], benefitsHi: ["राजसी पेड़", "इमारती लकड़ी", "हिमालयी मूल", "सजावटी"], growthTime: "8-12 years", soilType: "Mountain soil", maintenance: "Low", co2Absorption: 35, oxygenProduction: 370, image: deodarImg },
  { id: "chir", nameEn: "Chir Pine", nameTe: "చీర్ పైన్", nameHi: "चीड़", benefits: ["Resin production", "Timber", "Hill stabilization", "Evergreen"], benefitsTe: ["రాళ్ళ ఉత్పత్తి", "కలప", "కొండ స్థిరీకరణ", "శాశ్వత"], benefitsHi: ["राल उत्पादन", "इमारती लकड़ी", "पहाड़ी स्थिरीकरण", "सदाबहार"], growthTime: "6-8 years", soilType: "Mountain soil", maintenance: "Low", co2Absorption: 28, oxygenProduction: 300, image: chirImg },
  { id: "fir", nameEn: "Fir Tree", nameTe: "ఫిర్ చెట్టు", nameHi: "फर का पेड़", benefits: ["Christmas tree", "Symmetrical shape", "Aromatic", "Wildlife shelter"], benefitsTe: ["క్రిస్మస్ చెట్టు", "సమాన ఆకారం", "సుగంధం", "వన్యజీవుల ఆశ్రయం"], benefitsHi: ["क्रिसमस पेड़", "सममित आकार", "सुगंधित", "वन्यजीव आश्रय"], growthTime: "7-10 years", soilType: "Cool climate", maintenance: "Low", co2Absorption: 33, oxygenProduction: 350, image: firImg },
  { id: "spruce", nameEn: "Spruce Tree", nameTe: "స్ప్రూస్ చెట్టు", nameHi: "स्प्रूस का पेड़", benefits: ["Blue needles", "Timber wood", "Ornamental", "Cold hardy"], benefitsTe: ["నీలం ముళ్ళు", "కలప కలప", "అలంకార", "చల్లని కఠినం"], benefitsHi: ["नीली सुई", "इमारती लकड़ी", "सजावटी", "ठंडा हार्डी"], growthTime: "6-9 years", soilType: "Cool climate", maintenance: "Low", co2Absorption: 31, oxygenProduction: 330, image: spruceImg },
  { id: "maple", nameEn: "Maple Tree", nameTe: "మేపుల్ చెట్టు", nameHi: "मेपल का पेड़", benefits: ["Autumn colors", "Maple syrup", "Beautiful foliage", "Shade tree"], benefitsTe: ["శరదృతువు రంగులు", "మేపుల్ సిరప్", "అందమైన ఆకులు", "నీడ చెట్టు"], benefitsHi: ["शरद ऋतु के रंग", "मेपल सिरप", "सुंदर पत्तियां", "छाया पेड़"], growthTime: "10-15 years", soilType: "Rich soil", maintenance: "Moderate", co2Absorption: 38, oxygenProduction: 400, image: mapleImg },
  { id: "birch", nameEn: "Birch Tree", nameTe: "బిర్చ్ చెట్టు", nameHi: "सन्डूर का पेड़", benefits: ["White bark", "Graceful form", "Fast growing", "Ornamental"], benefitsTe: ["తెల్ల బెరడు", "దయగల రూపం", "వేగంగా పెరుగుతుంది", "అలంకార"], benefitsHi: ["सफेद छाल", "सुंदर रूप", "तेजी से बढ़ता", "सजावटी"], growthTime: "5-7 years", soilType: "Moist soil", maintenance: "Moderate water", co2Absorption: 26, oxygenProduction: 280, image: birchImg },
  { id: "willow", nameEn: "Willow Tree", nameTe: "విల్లో చెట్టు", nameHi: "विलो का पेड़", benefits: ["Graceful branches", "Water loving", "Erosion control", "Fast growing"], benefitsTe: ["దయగల శాఖలు", "నీటిని ప్రేమించేది", "కోత నియంత్రణ", "వేగంగా పెరుగుతుంది"], benefitsHi: ["सुंदर शाखाएं", "पानी प्रेमी", "कटाव नियंत्रण", "तेजी से बढ़ता"], growthTime: "3-5 years", soilType: "Wet soil", maintenance: "High water", co2Absorption: 29, oxygenProduction: 310, image: willowImg },
  { id: "poplar", nameEn: "Poplar Tree", nameTe: "పోప్లర్ చెట్టు", nameHi: "पॉपलर का पेड़", benefits: ["Fast growing", "Tall stature", "Windbreak", "Paper production"], benefitsTe: ["వేగంగా పెరుగుతుంది", "ఎత్తైన నిలబడటం", "గాలి అవరోధం", "కాగితం ఉత్పత్తి"], benefitsHi: ["तेजी से बढ़ता", "लंबा कद", "हवा रोक", "कागज उत्पादन"], growthTime: "4-6 years", soilType: "Various", maintenance: "Moderate", co2Absorption: 32, oxygenProduction: 340, image: poplarImg },
  { id: "elm", nameEn: "Elm Tree", nameTe: "ఎల్మ్ చెట్టు", nameHi: "एल्म का पेड़", benefits: ["Broad canopy", "Strong wood", "Urban tolerant", "Historic tree"], benefitsTe: ["విస్తృత చాప", "బలమైన కలప", "నగర సహనం", "చారిత్రక చెట్టు"], benefitsHi: ["व्यापक छत्र", "मजबूत लकड़ी", "शहरी सहिष्णु", "ऐतिहासिक पेड़"], growthTime: "8-12 years", soilType: "Rich soil", maintenance: "Moderate", co2Absorption: 36, oxygenProduction: 380, image: elmImg },
  { id: "ash", nameEn: "Ash Tree", nameTe: "ఆష్ చెట్టు", nameHi: "ऐश का पेड़", benefits: ["Durable wood", "Tall growth", "Beautiful form", "Timber use"], benefitsTe: ["మన్నికైన కలప", "ఎత్తైన పెరుగుదల", "అందమైన రూపం", "కలప వినియోగం"], benefitsHi: ["टिकाऊ लकड़ी", "लंबा विकास", "सुंदर रूप", "इमारती उपयोग"], growthTime: "7-10 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 34, oxygenProduction: 360, image: ashImg },
  { id: "walnut", nameEn: "Walnut Tree", nameTe: "వాల్‌నట్ చెట్టు", nameHi: "अखरोट का पेड़", benefits: ["Nutritious nuts", "Quality wood", "Shade provider", "High value"], benefitsTe: ["పోషకమైన గింజలు", "నాణ్యమైన కలప", "నీడ అందించడం", "అధిక విలువ"], benefitsHi: ["पौष्टिक मेवे", "गुणवत्ता लकड़ी", "छाया प्रदाता", "उच्च मूल्य"], growthTime: "8-12 years", soilType: "Deep soil", maintenance: "Moderate", co2Absorption: 37, oxygenProduction: 390, image: walnutImg },
  { id: "chestnut", nameEn: "Chestnut Tree", nameTe: "చెస్ట్‌నట్ చెట్టు", nameHi: "शाहबलूत का पेड़", benefits: ["Edible nuts", "Large canopy", "Historic value", "Wildlife food"], benefitsTe: ["తినదగిన గింజలు", "పెద్ద చాప", "చారిత్రక విలువ", "వన్యజీవుల ఆహారం"], benefitsHi: ["खाने योग्य नट", "बड़ी छत्र", "ऐतिहासिक मूल्य", "वन्यजीव भोजन"], growthTime: "7-10 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 35, oxygenProduction: 370, image: chestnutImg },
  { id: "cherry", nameEn: "Cherry Tree", nameTe: "చెర్రీ చెట్టు", nameHi: "चेरी का पेड़", benefits: ["Beautiful blossoms", "Sweet fruit", "Ornamental", "Spring beauty"], benefitsTe: ["అందమైన పువ్వులు", "తీయని పండు", "అలంకార", "వసంత అందం"], benefitsHi: ["सुंदर फूल", "मीठा फल", "सजावटी", "वसंत सुंदरता"], growthTime: "4-6 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 21, oxygenProduction: 230, image: cherryImg },
  { id: "plum", nameEn: "Plum Tree", nameTe: "ప్లమ్ చెట్టు", nameHi: "आलूबुखारा का पेड़", benefits: ["Juicy fruit", "Spring blossoms", "Easy to grow", "Compact size"], benefitsTe: ["రసమైన పండు", "వసంత పువ్వులు", "పెంచడం సులభం", "కాంపాక్ట్ పరిమాణం"], benefitsHi: ["रसीला फल", "वसंत फूल", "उगाना आसान", "कॉम्पैक्ट आकार"], growthTime: "3-5 years", soilType: "Loamy soil", maintenance: "Moderate", co2Absorption: 20, oxygenProduction: 220, image: plumImg },
  { id: "peach", nameEn: "Peach Tree", nameTe: "పీచ్ చెట్టు", nameHi: "आड़ू का पेड़", benefits: ["Sweet fruit", "Fuzzy skin", "Spring blooms", "Cold hardy"], benefitsTe: ["తీయని పండు", "రోమ చర్మం", "వసంత వికసించడం", "చల్లని కఠినం"], benefitsHi: ["मीठा फल", "मुलायम त्वचा", "वसंत फूल", "ठंडा हार्डी"], growthTime: "3-4 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 19, oxygenProduction: 210, image: peachImg },
  { id: "apricot", nameEn: "Apricot Tree", nameTe: "ఆప్రికాట్ చెట్టు", nameHi: "खुबानी का पेड़", benefits: ["Golden fruit", "Early bloomer", "Drought tolerant", "Vitamin A"], benefitsTe: ["బంగారు పండు", "ప్రారంభ వికసించడం", "కరువు సహనం", "విటమిన్ ఎ"], benefitsHi: ["सुनहरा फल", "जल्दी फूलने वाला", "सूखा सहिष्णु", "विटामिन ए"], growthTime: "3-5 years", soilType: "Sandy loam", maintenance: "Low water", co2Absorption: 18, oxygenProduction: 200, image: apricotImg },
  { id: "almond", nameEn: "Almond Tree", nameTe: "బాదం చెట్టు", nameHi: "बादाम का पेड़", benefits: ["Nutritious nuts", "Beautiful blossoms", "Drought resistant", "High protein"], benefitsTe: ["పోషకమైన గింజలు", "అందమైన పువ్వులు", "కరువు నిరోధకత", "అధిక ప్రోటీన్"], benefitsHi: ["पौष्टिक मेवे", "सुंदर फूल", "सूखा प्रतिरोधी", "उच्च प्रोटीन"], growthTime: "4-6 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 22, oxygenProduction: 240, image: almondImg },
  { id: "cashew", nameEn: "Cashew Tree", nameTe: "జీడి చెట్టు", nameHi: "काजू का पेड़", benefits: ["Cashew nuts", "Tropical fruit", "Economic crop", "Oil production"], benefitsTe: ["జీడి గింజలు", "ఉష్ణమండల పండు", "ఆర్థిక పంట", "నూనె ఉత్పత్తి"], benefitsHi: ["काजू", "उष्णकटिबंधीय फल", "आर्थिक फसल", "तेल उत्पादन"], growthTime: "3-5 years", soilType: "Sandy soil", maintenance: "Low", co2Absorption: 20, oxygenProduction: 220, image: cashewImg },
  { id: "pistachio", nameEn: "Pistachio Tree", nameTe: "పిస్తా చెట్టు", nameHi: "पिस्ता का पेड़", benefits: ["Valuable nuts", "Drought tolerant", "Long-lived", "Healthy snack"], benefitsTe: ["విలువైన గింజలు", "కరువు సహనం", "దీర్ఘాయువు", "ఆరోగ్యకర స్నాక్"], benefitsHi: ["मूल्यवान मेवे", "सूखा सहिष्णु", "दीर्घजीवी", "स्वस्थ नाश्ता"], growthTime: "5-8 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 23, oxygenProduction: 250, image: pistachioImg },
  { id: "olive", nameEn: "Olive Tree", nameTe: "ఆలివ్ చెట్టు", nameHi: "जैतून का पेड़", benefits: ["Olive oil", "Mediterranean beauty", "Long-lived", "Drought resistant"], benefitsTe: ["ఆలివ్ నూనె", "మెడిటెర్రేనియన్ అందం", "దీర్ఘాయువు", "కరువు నిరోధకత"], benefitsHi: ["जैतून का तेल", "भूमध्यसागरीय सुंदरता", "दीर्घजीवी", "सूखा प्रतिरोधी"], growthTime: "4-7 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 21, oxygenProduction: 230, image: oliveImg },
  { id: "date", nameEn: "Date Palm", nameTe: "ఖర్జూరం చెట్టు", nameHi: "खजूर का पेड़", benefits: ["Sweet dates", "Desert adapted", "Historic crop", "High energy"], benefitsTe: ["తీయని ఖర్జూరం", "ఎడారి అనుకూలం", "చారిత్రక పంట", "అధిక శక్తి"], benefitsHi: ["मीठा खजूर", "रेगिस्तान अनुकूलित", "ऐतिहासिक फसल", "उच्च ऊर्जा"], growthTime: "4-8 years", soilType: "Sandy soil", maintenance: "Moderate", co2Absorption: 24, oxygenProduction: 260, image: dateImg },
  { id: "avocado", nameEn: "Avocado Tree", nameTe: "అవకాడో చెట్టు", nameHi: "एवोकाडो का पेड़", benefits: ["Healthy fats", "Creamy fruit", "Nutritious", "Popular food"], benefitsTe: ["ఆరోగ్యకర కొవ్వులు", "క్రీమీ పండు", "పోషకమైనది", "ప్రసిద్ధ ఆహారం"], benefitsHi: ["स्वस्थ वसा", "मलाईदार फल", "पौष्टिक", "लोकप्रिय भोजन"], growthTime: "3-5 years", soilType: "Well-drained", maintenance: "Regular water", co2Absorption: 22, oxygenProduction: 240, image: avocadoImg },
  { id: "custard-apple", nameEn: "Custard Apple Tree", nameTe: "సీతాఫలం చెట్టు", nameHi: "शरीफा का पेड़", benefits: ["Sweet pulp", "Nutritious", "Easy to grow", "Tropical delight"], benefitsTe: ["తీయని గుజ్జు", "పోషకమైనది", "పెంచడం సులభం", "ఉష్ణమండల ఆనందం"], benefitsHi: ["मीठा गूदा", "पौष्टिक", "उगाना आसान", "उष्णकटिबंधीय आनंद"], growthTime: "3-4 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 17, oxygenProduction: 190, image: custardAppleImg },
  { id: "sapota", nameEn: "Sapota Tree", nameTe: "సపోటా చెట్టు", nameHi: "चीकू का पेड़", benefits: ["Sweet fruit", "Brown flesh", "Energy boost", "Tropical fruit"], benefitsTe: ["తీయని పండు", "గోధుమ మాంసం", "శక్తి బూస్ట్", "ఉష్ణమండల పండు"], benefitsHi: ["मीठा फल", "भूरा गूदा", "ऊर्जा बूस्ट", "उष्णकटिबंधीय फल"], growthTime: "5-7 years", soilType: "Sandy loam", maintenance: "Moderate", co2Absorption: 19, oxygenProduction: 210, image: sapotaImg },
  { id: "litchi", nameEn: "Litchi Tree", nameTe: "లీచీ చెట్టు", nameHi: "लीची का पेड़", benefits: ["Sweet fruit", "Red shell", "Vitamin C", "Tropical delicacy"], benefitsTe: ["తీయని పండు", "ఎరుపు కవచం", "విటమిన్ సి", "ఉష్ణమండల రుచి"], benefitsHi: ["मीठा फल", "लाल खोल", "विटामिन सी", "उष्णकटिबंधीय स्वाद"], growthTime: "5-7 years", soilType: "Well-drained", maintenance: "Moderate water", co2Absorption: 20, oxygenProduction: 220, image: litchiImg },
  { id: "longan", nameEn: "Longan Tree", nameTe: "లాంగన్ చెట్టు", nameHi: "लोंगन का पेड़", benefits: ["Dragon eye", "Sweet taste", "Medicinal", "Tropical fruit"], benefitsTe: ["డ్రాగన్ కన్ను", "తీయని రుచి", "ఔషధం", "ఉష్ణమండల పండు"], benefitsHi: ["ड्रैगन आई", "मीठा स्वाद", "औषधीय", "उष्णकटिबंधीय फल"], growthTime: "4-6 years", soilType: "Sandy loam", maintenance: "Regular water", co2Absorption: 18, oxygenProduction: 200, image: longanImg },
  { id: "rambutan", nameEn: "Rambutan Tree", nameTe: "రాంబుటాన్ చెట్టు", nameHi: "रामबूटन का पेड़", benefits: ["Hairy fruit", "Sweet taste", "Exotic", "Vitamin C"], benefitsTe: ["వెంట్రుకల పండు", "తీయని రుచి", "అన్యదేశ", "విటమిన్ సి"], benefitsHi: ["बालों वाला फल", "मीठा स्वाद", "विदेशी", "विटामिन सी"], growthTime: "5-6 years", soilType: "Rich soil", maintenance: "Humid conditions", co2Absorption: 19, oxygenProduction: 210, image: rambutanImg },
  // New trees 57-100 with unique images
  { id: "durian", nameEn: "Durian Tree", nameTe: "డూరియన్ చెట్టు", nameHi: "डुरियन का पेड़", benefits: ["King of fruits", "High nutrition", "Strong aroma", "Tropical delicacy"], benefitsTe: ["పండ్ల రాజు", "అధిక పోషణ", "బలమైన సువాసన", "ఉష్ణమండల రుచి"], benefitsHi: ["फलों का राजा", "उच्च पोषण", "तीव्र सुगंध", "उष्णकटिबंधीय स्वाद"], growthTime: "5-8 years", soilType: "Rich soil", maintenance: "High water", co2Absorption: 28, oxygenProduction: 300, image: durianImg },
  { id: "mangosteen", nameEn: "Mangosteen Tree", nameTe: "మాంగోస్టీన్ చెట్టు", nameHi: "मैंगोस्टीन का पेड़", benefits: ["Queen of fruits", "Antioxidants", "Sweet taste", "Medicinal"], benefitsTe: ["పండ్ల రాణి", "యాంటీఆక్సిడెంట్లు", "తీయని రుచి", "ఔషధం"], benefitsHi: ["फलों की रानी", "एंटीऑक्सीडेंट", "मीठा स्वाद", "औषधीय"], growthTime: "8-10 years", soilType: "Rich soil", maintenance: "High water", co2Absorption: 25, oxygenProduction: 270, image: mangosteenImg },
  { id: "star-fruit", nameEn: "Star Fruit Tree", nameTe: "స్టార్ ఫ్రూట్ చెట్టు", nameHi: "स्टार फ्रूट का पेड़", benefits: ["Star-shaped fruit", "Vitamin C", "Ornamental", "Low calories"], benefitsTe: ["నక్షత్ర ఆకారపు పండు", "విటమిన్ సి", "అలంకార", "తక్కువ కేలరీలు"], benefitsHi: ["तारे के आकार का फल", "विटामिन सी", "सजावटी", "कम कैलोरी"], growthTime: "3-4 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 18, oxygenProduction: 200, image: starFruitImg },
  { id: "dragon-fruit", nameEn: "Dragon Fruit Plant", nameTe: "డ్రాగన్ ఫ్రూట్ మొక్క", nameHi: "ड्रैगन फ्रूट का पौधा", benefits: ["Exotic fruit", "Antioxidants", "Low calories", "Beautiful flowers"], benefitsTe: ["అన్యదేశ పండు", "యాంటీఆక్సిడెంట్లు", "తక్కువ కేలరీలు", "అందమైన పువ్వులు"], benefitsHi: ["विदेशी फल", "एंटीऑक्सीडेंट", "कम कैलोरी", "सुंदर फूल"], growthTime: "2-3 years", soilType: "Sandy soil", maintenance: "Low water", co2Absorption: 12, oxygenProduction: 140, image: dragonFruitImg },
  { id: "passion-fruit", nameEn: "Passion Fruit Vine", nameTe: "ప్యాషన్ ఫ్రూట్ తీగ", nameHi: "पैशन फ्रूट बेल", benefits: ["Unique flavor", "Vitamin C", "Fast growing", "Beautiful flowers"], benefitsTe: ["ప్రత్యేక రుచి", "విటమిన్ సి", "వేగంగా పెరుగుతుంది", "అందమైన పువ్వులు"], benefitsHi: ["अनोखा स्वाद", "विटामिन सी", "तेजी से बढ़ता", "सुंदर फूल"], growthTime: "1-2 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 10, oxygenProduction: 120, image: passionFruitImg },
  { id: "kiwi", nameEn: "Kiwi Vine", nameTe: "కివీ తీగ", nameHi: "कीवी बेल", benefits: ["Vitamin C", "Fuzzy fruit", "Cool climate", "Nutritious"], benefitsTe: ["విటమిన్ సి", "రోమ పండు", "చల్లని వాతావరణం", "పోషకమైనది"], benefitsHi: ["विटामिन सी", "मुलायम फल", "ठंडी जलवायु", "पौष्टिक"], growthTime: "3-5 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 14, oxygenProduction: 160, image: kiwiImg },
  { id: "persimmon", nameEn: "Persimmon Tree", nameTe: "పర్సిమ్మన్ చెట్టు", nameHi: "पर्सिमन का पेड़", benefits: ["Sweet fruit", "Autumn color", "Ornamental", "Nutritious"], benefitsTe: ["తీయని పండు", "శరదృతువు రంగు", "అలంకార", "పోషకమైనది"], benefitsHi: ["मीठा फल", "शरद रंग", "सजावटी", "पौष्टिक"], growthTime: "4-6 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 22, oxygenProduction: 240, image: persimmonImg },
  { id: "mulberry", nameEn: "Mulberry Tree", nameTe: "మల్బరీ చెట్టు", nameHi: "शहतूत का पेड़", benefits: ["Sweet berries", "Silk production", "Fast growing", "Wildlife food"], benefitsTe: ["తీయని బెర్రీలు", "పట్టు ఉత్పత్తి", "వేగంగా పెరుగుతుంది", "వన్యజీవుల ఆహారం"], benefitsHi: ["मीठे बेर", "रेशम उत्पादन", "तेजी से बढ़ता", "वन्यजीव भोजन"], growthTime: "3-5 years", soilType: "Various", maintenance: "Low", co2Absorption: 24, oxygenProduction: 260, image: mulberryImg },
  { id: "blackberry", nameEn: "Blackberry Bush", nameTe: "బ్లాక్‌బెర్రీ పొద", nameHi: "ब्लैकबेरी झाड़ी", benefits: ["Antioxidants", "Sweet berries", "Easy to grow", "Ground cover"], benefitsTe: ["యాంటీఆక్సిడెంట్లు", "తీయని బెర్రీలు", "పెంచడం సులభం", "గ్రౌండ్ కవర్"], benefitsHi: ["एंटीऑक्सीडेंट", "मीठे बेर", "उगाना आसान", "ग्राउंड कवर"], growthTime: "1-2 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 8, oxygenProduction: 100, image: blackberryImg },
  { id: "raspberry", nameEn: "Raspberry Bush", nameTe: "రాస్ప్‌బెర్రీ పొద", nameHi: "रास्पबेरी झाड़ी", benefits: ["Vitamin C", "Delicious berries", "Cold hardy", "Multiple harvests"], benefitsTe: ["విటమిన్ సి", "రుచికరమైన బెర్రీలు", "చల్లని కఠినం", "అనేక పంటలు"], benefitsHi: ["विटामिन सी", "स्वादिष्ट बेर", "ठंडा हार्डी", "कई फसलें"], growthTime: "1-2 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 8, oxygenProduction: 100, image: raspberryImg },
  { id: "gooseberry", nameEn: "Gooseberry Bush", nameTe: "గూస్‌బెర్రీ పొద", nameHi: "आंवला झाड़ी", benefits: ["Vitamin C", "Tart flavor", "Cold hardy", "Preserves"], benefitsTe: ["విటమిన్ సి", "పులుపు రుచి", "చల్లని కఠినం", "ప్రిజర్వ్స్"], benefitsHi: ["विटामिन सी", "खट्टा स्वाद", "ठंडा हार्डी", "संरक्षित"], growthTime: "2-3 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 7, oxygenProduction: 90, image: gooseberryImg },
  { id: "blueberry", nameEn: "Blueberry Bush", nameTe: "బ్లూబెర్రీ పొద", nameHi: "ब्लूबेरी झाड़ी", benefits: ["Antioxidants", "Brain health", "Sweet berries", "Ornamental"], benefitsTe: ["యాంటీఆక్సిడెంట్లు", "మెదడు ఆరోగ్యం", "తీయని బెర్రీలు", "అలంకార"], benefitsHi: ["एंटीऑक्सीडेंट", "मस्तिष्क स्वास्थ्य", "मीठे बेर", "सजावटी"], growthTime: "2-3 years", soilType: "Acidic soil", maintenance: "Moderate", co2Absorption: 9, oxygenProduction: 110, image: blueberryImg },
  { id: "cranberry", nameEn: "Cranberry Bush", nameTe: "క్రాన్‌బెర్రీ పొద", nameHi: "क्रैनबेरी झाड़ी", benefits: ["UTI prevention", "Antioxidants", "Tart flavor", "Wetland plant"], benefitsTe: ["UTI నివారణ", "యాంటీఆక్సిడెంట్లు", "పులుపు రుచి", "చిత్తడి మొక్క"], benefitsHi: ["UTI रोकथाम", "एंटीऑक्सीडेंट", "खट्टा स्वाद", "आर्द्रभूमि पौधा"], growthTime: "2-3 years", soilType: "Acidic wet soil", maintenance: "High water", co2Absorption: 6, oxygenProduction: 80, image: cranberryImg },
  { id: "elderberry", nameEn: "Elderberry Tree", nameTe: "ఎల్డర్‌బెర్రీ చెట్టు", nameHi: "एल्डरबेरी का पेड़", benefits: ["Immune boost", "Medicinal", "Wildlife food", "Fast growing"], benefitsTe: ["రోగనిరోధక శక్తి", "ఔషధం", "వన్యజీవుల ఆహారం", "వేగంగా పెరుగుతుంది"], benefitsHi: ["प्रतिरक्षा बूस्ट", "औषधीय", "वन्यजीव भोजन", "तेजी से बढ़ता"], growthTime: "2-4 years", soilType: "Moist soil", maintenance: "Low", co2Absorption: 18, oxygenProduction: 200, image: elderberryImg },
  { id: "hawthorn", nameEn: "Hawthorn Tree", nameTe: "హాథార్న్ చెట్టు", nameHi: "नागफनी का पेड़", benefits: ["Heart health", "Berries", "Hedge plant", "Wildlife habitat"], benefitsTe: ["గుండె ఆరోగ్యం", "బెర్రీలు", "హెడ్జ్ మొక్క", "వన్యజీవుల నివాసం"], benefitsHi: ["हृदय स्वास्थ्य", "बेर", "हेज पौधा", "वन्यजीव आवास"], growthTime: "4-6 years", soilType: "Various", maintenance: "Low", co2Absorption: 20, oxygenProduction: 220, image: hawthornImg },
  { id: "juniper", nameEn: "Juniper Tree", nameTe: "జునిపర్ చెట్టు", nameHi: "जुनिपर का पेड़", benefits: ["Aromatic berries", "Evergreen", "Drought tolerant", "Gin flavoring"], benefitsTe: ["సుగంధ బెర్రీలు", "శాశ్వత ఆకులు", "కరువు సహనం", "జిన్ ఫ్లేవరింగ్"], benefitsHi: ["सुगंधित बेर", "सदाबहार", "सूखा सहिष्णु", "जिन स्वाद"], growthTime: "5-8 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 22, oxygenProduction: 240, image: juniperImg },
  { id: "yew", nameEn: "Yew Tree", nameTe: "యూ చెట్టు", nameHi: "यू का पेड़", benefits: ["Long-lived", "Medicinal compounds", "Ornamental", "Dense foliage"], benefitsTe: ["దీర్ఘాయువు", "ఔషధ సమ్మేళనాలు", "అలంకార", "దట్టమైన ఆకులు"], benefitsHi: ["दीर्घजीवी", "औषधीय यौगिक", "सजावटी", "घने पत्ते"], growthTime: "8-15 years", soilType: "Various", maintenance: "Low", co2Absorption: 26, oxygenProduction: 280, image: yewImg },
  { id: "sequoia", nameEn: "Sequoia Tree", nameTe: "సెక్వోయా చెట్టు", nameHi: "सिकोया का पेड़", benefits: ["Tallest trees", "Ancient species", "Carbon storage", "Majestic beauty"], benefitsTe: ["ఎత్తైన చెట్లు", "పురాతన జాతులు", "కార్బన్ నిల్వ", "గంభీరమైన అందం"], benefitsHi: ["सबसे ऊंचे पेड़", "प्राचीन प्रजाति", "कार्बन भंडारण", "राजसी सुंदरता"], growthTime: "20-50 years", soilType: "Rich moist soil", maintenance: "Moderate", co2Absorption: 100, oxygenProduction: 1000, image: sequoiaImg },
  { id: "redwood", nameEn: "Redwood Tree", nameTe: "రెడ్‌వుడ్ చెట్టు", nameHi: "रेडवुड का पेड़", benefits: ["Giant trees", "Durable wood", "Fire resistant", "Carbon capture"], benefitsTe: ["పెద్ద చెట్లు", "మన్నికైన కలప", "అగ్ని నిరోధకత", "కార్బన్ క్యాప్చర్"], benefitsHi: ["विशाल पेड़", "टिकाऊ लकड़ी", "अग्नि प्रतिरोधी", "कार्बन कैप्चर"], growthTime: "15-30 years", soilType: "Moist soil", maintenance: "Low", co2Absorption: 80, oxygenProduction: 850, image: redwoodImg },
  { id: "cypress", nameEn: "Cypress Tree", nameTe: "సైప్రస్ చెట్టు", nameHi: "सरू का पेड़", benefits: ["Elegant shape", "Evergreen", "Water tolerant", "Ornamental"], benefitsTe: ["నాజూకైన ఆకారం", "శాశ్వత ఆకులు", "నీటి సహనం", "అలంకార"], benefitsHi: ["सुंदर आकार", "सदाबहार", "पानी सहिष्णु", "सजावटी"], growthTime: "6-10 years", soilType: "Wet soil", maintenance: "Low", co2Absorption: 30, oxygenProduction: 320, image: cypressImg },
  { id: "larch", nameEn: "Larch Tree", nameTe: "లార్చ్ చెట్టు", nameHi: "लार्च का पेड़", benefits: ["Deciduous conifer", "Autumn gold", "Durable wood", "Mountain tree"], benefitsTe: ["ఆకురాల్చే కోనిఫర్", "శరదృతువు బంగారు", "మన్నికైన కలప", "పర్వత చెట్టు"], benefitsHi: ["पर्णपाती शंकुवृक्ष", "शरद सोना", "टिकाऊ लकड़ी", "पहाड़ी पेड़"], growthTime: "8-12 years", soilType: "Mountain soil", maintenance: "Low", co2Absorption: 28, oxygenProduction: 300, image: larchImg },
  { id: "hemlock", nameEn: "Hemlock Tree", nameTe: "హెమ్లాక్ చెట్టు", nameHi: "हेमलॉक का पेड़", benefits: ["Shade tolerant", "Graceful form", "Wildlife shelter", "Cool climate"], benefitsTe: ["నీడ సహనం", "దయగల రూపం", "వన్యజీవుల ఆశ్రయం", "చల్లని వాతావరణం"], benefitsHi: ["छाया सहिष्णु", "सुंदर रूप", "वन्यजीव आश्रय", "ठंडी जलवायु"], growthTime: "10-15 years", soilType: "Acidic soil", maintenance: "Moderate", co2Absorption: 32, oxygenProduction: 340, image: hemlockImg },
  { id: "acacia", nameEn: "Acacia Tree", nameTe: "అకేషియా చెట్టు", nameHi: "बबूल का पेड़", benefits: ["Nitrogen fixing", "Drought tolerant", "African savanna", "Fast growing"], benefitsTe: ["నత్రజని స్థిరీకరణ", "కరువు సహనం", "ఆఫ్రికన్ సవన్నా", "వేగంగా పెరుగుతుంది"], benefitsHi: ["नाइट्रोजन स्थिरीकरण", "सूखा सहिष्णु", "अफ्रीकी सवाना", "तेजी से बढ़ता"], growthTime: "3-5 years", soilType: "Sandy soil", maintenance: "Low", co2Absorption: 25, oxygenProduction: 270, image: acaciaImg },
  { id: "mimosa", nameEn: "Mimosa Tree", nameTe: "మిమోసా చెట్టు", nameHi: "मिमोसा का पेड़", benefits: ["Pink flowers", "Fast growing", "Ornamental", "Fragrant"], benefitsTe: ["గులాబీ పువ్వులు", "వేగంగా పెరుగుతుంది", "అలంకార", "సుగంధం"], benefitsHi: ["गुलाबी फूल", "तेजी से बढ़ता", "सजावटी", "सुगंधित"], growthTime: "3-5 years", soilType: "Various", maintenance: "Low", co2Absorption: 20, oxygenProduction: 220, image: mimosaImg },
  { id: "wattle", nameEn: "Wattle Tree", nameTe: "వాటిల్ చెట్టు", nameHi: "वाटल का पेड़", benefits: ["Yellow flowers", "Australian native", "Fast growing", "Nitrogen fixing"], benefitsTe: ["పసుపు పువ్వులు", "ఆస్ట్రేలియన్ స్థానికం", "వేగంగా పెరుగుతుంది", "నత్రజని స్థిరీకరణ"], benefitsHi: ["पीले फूल", "ऑस्ट्रेलियाई मूल", "तेजी से बढ़ता", "नाइट्रोजन स्थिरीकरण"], growthTime: "3-5 years", soilType: "Various", maintenance: "Low", co2Absorption: 22, oxygenProduction: 240, image: wattleImg },
  { id: "gum", nameEn: "Gum Tree", nameTe: "గమ్ చెట్టు", nameHi: "गम का पेड़", benefits: ["Smooth bark", "Essential oils", "Fast growing", "Wildlife habitat"], benefitsTe: ["మృదువైన బెరడు", "ఎసెన్షియల్ ఆయిల్స్", "వేగంగా పెరుగుతుంది", "వన్యజీవుల నివాసం"], benefitsHi: ["चिकनी छाल", "आवश्यक तेल", "तेजी से बढ़ता", "वन्यजीव आवास"], growthTime: "4-6 years", soilType: "Various", maintenance: "Low", co2Absorption: 28, oxygenProduction: 300, image: gumImg },
  { id: "bottlebrush", nameEn: "Bottlebrush Tree", nameTe: "బాటిల్ బ్రష్ చెట్టు", nameHi: "बॉटलब्रश का पेड़", benefits: ["Red flowers", "Bird attracting", "Drought tolerant", "Ornamental"], benefitsTe: ["ఎరుపు పువ్వులు", "పక్షులను ఆకర్షించేది", "కరువు సహనం", "అలంకార"], benefitsHi: ["लाल फूल", "पक्षी आकर्षक", "सूखा सहिष्णु", "सजावटी"], growthTime: "3-5 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 18, oxygenProduction: 200, image: bottlebrushImg },
  { id: "tea-tree", nameEn: "Tea Tree", nameTe: "టీ ట్రీ", nameHi: "टी ट्री", benefits: ["Medicinal oil", "Antiseptic", "Aromatic", "Easy to grow"], benefitsTe: ["ఔషధ నూనె", "యాంటీసెప్టిక్", "సుగంధం", "పెంచడం సులభం"], benefitsHi: ["औषधीय तेल", "एंटीसेप्टिक", "सुगंधित", "उगाना आसान"], growthTime: "3-5 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 16, oxygenProduction: 180, image: teaTreeImg },
  { id: "manuka", nameEn: "Manuka Tree", nameTe: "మానుకా చెట్టు", nameHi: "मनुका का पेड़", benefits: ["Manuka honey", "Medicinal", "New Zealand native", "Beautiful flowers"], benefitsTe: ["మానుకా తేనె", "ఔషధం", "న్యూజిలాండ్ స్థానికం", "అందమైన పువ్వులు"], benefitsHi: ["मनुका शहद", "औषधीय", "न्यूजीलैंड मूल", "सुंदर फूल"], growthTime: "3-5 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 15, oxygenProduction: 170, image: manukaImg },
  { id: "karri", nameEn: "Karri Tree", nameTe: "కారీ చెట్టు", nameHi: "कर्री का पेड़", benefits: ["Tall eucalyptus", "Premium timber", "Australian native", "Smooth bark"], benefitsTe: ["ఎత్తైన యూకలిప్టస్", "ప్రీమియం కలప", "ఆస్ట్రేలియన్ స్థానికం", "మృదువైన బెరడు"], benefitsHi: ["ऊंचा यूकेलिप्टस", "प्रीमियम लकड़ी", "ऑस्ट्रेलियाई मूल", "चिकनी छाल"], growthTime: "10-15 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 40, oxygenProduction: 420, image: karriImg },
  { id: "jarrah", nameEn: "Jarrah Tree", nameTe: "జర్రా చెట్టు", nameHi: "जर्रा का पेड़", benefits: ["Durable wood", "Fire resistant", "Australian native", "Honey production"], benefitsTe: ["మన్నికైన కలప", "అగ్ని నిరోధకత", "ఆస్ట్రేలియన్ స్థానికం", "తేనె ఉత్పత్తి"], benefitsHi: ["टिकाऊ लकड़ी", "अग्नि प्रतिरोधी", "ऑस्ट्रेलियाई मूल", "शहद उत्पादन"], growthTime: "10-15 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 38, oxygenProduction: 400, image: jarrahImg },
  { id: "blackwood", nameEn: "Blackwood Tree", nameTe: "బ్లాక్‌వుడ్ చెట్టు", nameHi: "ब्लैकवुड का पेड़", benefits: ["Dark wood", "Furniture wood", "Australian native", "Fast growing"], benefitsTe: ["నల్ల కలప", "ఫర్నీచర్ కలప", "ఆస్ట్రేలియన్ స్థానికం", "వేగంగా పెరుగుతుంది"], benefitsHi: ["काली लकड़ी", "फर्नीचर लकड़ी", "ऑस्ट्रेलियाई मूल", "तेजी से बढ़ता"], growthTime: "8-12 years", soilType: "Various", maintenance: "Low", co2Absorption: 32, oxygenProduction: 340, image: blackwoodImg },
  { id: "silver-wattle", nameEn: "Silver Wattle Tree", nameTe: "సిల్వర్ వాటిల్ చెట్టు", nameHi: "सिल्वर वाटल का पेड़", benefits: ["Silvery foliage", "Yellow flowers", "Fast growing", "Nitrogen fixing"], benefitsTe: ["వెండి ఆకులు", "పసుపు పువ్వులు", "వేగంగా పెరుగుతుంది", "నత్రజని స్థిరీకరణ"], benefitsHi: ["चांदी पत्ते", "पीले फूल", "तेजी से बढ़ता", "नाइट्रोजन स्थिरीकरण"], growthTime: "3-5 years", soilType: "Various", maintenance: "Low", co2Absorption: 24, oxygenProduction: 260, image: silverWattleImg },
  { id: "ironwood", nameEn: "Ironwood Tree", nameTe: "ఐరన్‌వుడ్ చెట్టు", nameHi: "आयरनवुड का पेड़", benefits: ["Extremely hard wood", "Dense canopy", "Long-lived", "Erosion control"], benefitsTe: ["చాలా గట్టి కలప", "దట్టమైన చాప", "దీర్ఘాయువు", "కోత నియంత్రణ"], benefitsHi: ["बेहद कठोर लकड़ी", "घना छत्र", "दीर्घजीवी", "कटाव नियंत्रण"], growthTime: "10-20 years", soilType: "Various", maintenance: "Low", co2Absorption: 35, oxygenProduction: 370, image: ironwoodImg },
  { id: "ebony", nameEn: "Ebony Tree", nameTe: "ఎబోనీ చెట్టు", nameHi: "आबनूस का पेड़", benefits: ["Black wood", "High value", "Dense wood", "Musical instruments"], benefitsTe: ["నల్ల కలప", "అధిక విలువ", "దట్టమైన కలప", "సంగీత వాయిద్యాలు"], benefitsHi: ["काली लकड़ी", "उच्च मूल्य", "घनी लकड़ी", "संगीत वाद्ययंत्र"], growthTime: "15-25 years", soilType: "Rich soil", maintenance: "Moderate", co2Absorption: 30, oxygenProduction: 320, image: ebonyImg },
  { id: "boxwood", nameEn: "Boxwood Shrub", nameTe: "బాక్స్‌వుడ్ పొద", nameHi: "बक्सवुड झाड़ी", benefits: ["Topiary plant", "Dense foliage", "Slow growing", "Formal gardens"], benefitsTe: ["టోపియరీ మొక్క", "దట్టమైన ఆకులు", "నెమ్మదిగా పెరుగుతుంది", "ఫార్మల్ గార్డెన్స్"], benefitsHi: ["टोपियरी पौधा", "घने पत्ते", "धीरे बढ़ता", "औपचारिक उद्यान"], growthTime: "5-10 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 12, oxygenProduction: 140, image: boxwoodImg },
  { id: "holly", nameEn: "Holly Tree", nameTe: "హోలీ చెట్టు", nameHi: "होली का पेड़", benefits: ["Red berries", "Evergreen", "Christmas symbol", "Wildlife food"], benefitsTe: ["ఎరుపు బెర్రీలు", "శాశ్వత ఆకులు", "క్రిస్మస్ గుర్తు", "వన్యజీవుల ఆహారం"], benefitsHi: ["लाल बेर", "सदाबहार", "क्रिसमस प्रतीक", "वन्यजीव भोजन"], growthTime: "5-10 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 20, oxygenProduction: 220, image: hollyImg },
  { id: "magnolia", nameEn: "Magnolia Tree", nameTe: "మాగ్నోలియా చెట్టు", nameHi: "मैगनोलिया का पेड़", benefits: ["Large flowers", "Ancient species", "Fragrant", "Ornamental"], benefitsTe: ["పెద్ద పువ్వులు", "పురాతన జాతులు", "సుగంధం", "అలంకార"], benefitsHi: ["बड़े फूल", "प्राचीन प्रजाति", "सुगंधित", "सजावटी"], growthTime: "5-10 years", soilType: "Rich soil", maintenance: "Moderate", co2Absorption: 28, oxygenProduction: 300, image: magnoliaImg },
  { id: "dogwood", nameEn: "Dogwood Tree", nameTe: "డాగ్‌వుడ్ చెట్టు", nameHi: "डॉगवुड का पेड़", benefits: ["Spring flowers", "Autumn color", "Wildlife food", "Ornamental"], benefitsTe: ["వసంత పువ్వులు", "శరదృతువు రంగు", "వన్యజీవుల ఆహారం", "అలంకార"], benefitsHi: ["वसंत फूल", "शरद रंग", "वन्यजीव भोजन", "सजावटी"], growthTime: "4-7 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 22, oxygenProduction: 240, image: dogwoodImg },
  { id: "redbud", nameEn: "Redbud Tree", nameTe: "రెడ్‌బడ్ చెట్టు", nameHi: "रेडबड का पेड़", benefits: ["Pink spring flowers", "Heart-shaped leaves", "Compact size", "Native beauty"], benefitsTe: ["గులాబీ వసంత పువ్వులు", "గుండె ఆకారపు ఆకులు", "కాంపాక్ట్ పరిమాణం", "స్థానిక అందం"], benefitsHi: ["गुलाबी वसंत फूल", "दिल के आकार की पत्तियां", "कॉम्पैक्ट आकार", "देसी सुंदरता"], growthTime: "4-7 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 18, oxygenProduction: 200, image: redbudImg },
  { id: "smoke-tree", nameEn: "Smoke Tree", nameTe: "స్మోక్ ట్రీ", nameHi: "स्मोक ट्री", benefits: ["Fluffy plumes", "Purple foliage", "Drought tolerant", "Ornamental"], benefitsTe: ["మృదువైన గుత్తులు", "ఊదా ఆకులు", "కరువు సహనం", "అలంకార"], benefitsHi: ["मुलायम गुच्छे", "बैंगनी पत्ते", "सूखा सहिष्णु", "सजावटी"], growthTime: "4-6 years", soilType: "Well-drained", maintenance: "Low", co2Absorption: 16, oxygenProduction: 180, image: smokeTreeImg },
  { id: "rosewood", nameEn: "Rosewood Tree", nameTe: "రోజ్‌వుడ్ చెట్టు", nameHi: "शीशम का पेड़", benefits: ["Premium furniture wood", "Aromatic", "Durable", "High value"], benefitsTe: ["ప్రీమియం ఫర్నీచర్ కలప", "సుగంధం", "మన్నికైనది", "అధిక విలువ"], benefitsHi: ["प्रीमियम फर्नीचर लकड़ी", "सुगंधित", "टिकाऊ", "उच्च मूल्य"], growthTime: "10-15 years", soilType: "Well-drained", maintenance: "Moderate", co2Absorption: 35, oxygenProduction: 370, image: rosewoodImg },
  { id: "sycamore", nameEn: "Sycamore Tree", nameTe: "సైకామోర్ చెట్టు", nameHi: "गूलर का पेड़", benefits: ["Mottled bark", "Large leaves", "Shade tree", "Urban tolerant"], benefitsTe: ["మచ్చలు ఉన్న బెరడు", "పెద్ద ఆకులు", "నీడ చెట్టు", "నగర సహనం"], benefitsHi: ["धब्बेदार छाल", "बड़े पत्ते", "छाया पेड़", "शहरी सहिष्णु"], growthTime: "8-12 years", soilType: "Various", maintenance: "Low", co2Absorption: 38, oxygenProduction: 400, image: sycamoreImg },
  { id: "hickory", nameEn: "Hickory Tree", nameTe: "హిక్కరీ చెట్టు", nameHi: "हिकोरी का पेड़", benefits: ["Edible nuts", "Strong wood", "Autumn color", "Smoking wood"], benefitsTe: ["తినదగిన గింజలు", "బలమైన కలప", "శరదృతువు రంగు", "స్మోకింగ్ వుడ్"], benefitsHi: ["खाने योग्य नट", "मजबूत लकड़ी", "शरद रंग", "स्मोकिंग वुड"], growthTime: "10-15 years", soilType: "Deep soil", maintenance: "Low", co2Absorption: 36, oxygenProduction: 380, image: hickoryImg },
];
